  version: "3.8"

  services:
    redis:
      image: redis:7
      container_name: devlogs-redis
      ports:
        - "6379:6379"
    postgres:
      image: postgres:15
      container_name: devlogs-postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: devlogs
        POSTGRES_PASSWORD: devlogs
        POSTGRES_DB: logsdb
      volumes:
        - pgdata:/var/lib/postgresql/data
    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: redis-commander
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
      depends_on:
        - redis

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: devlogs-pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@devlogs.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "8080:80"
      depends_on:
        - postgres
      volumes:
        - pgadmin_data:/var/lib/pgadmin
  volumes:
    pgdata:
    pgadmin_data:
